# import handcalcs.render # Removed to avoid IPython dependency error
from handcalcs.decorator import handcalc
import os

@handcalc(jupyter_display=False)
def calculate_column_capacity_latex(fc, fy, b, h, d_bar, n_top, n_bot, n_side, cover):
    """
    Calculates representative column properties for the report.
    Note: Exact interaction diagram is complex iterative math.
    This function demonstrates the checking of a specific load point 
    or just calculates section properties for the report.
    """
    # 1. Geometry Properties
    # ----------------------
    A_g = b * h  # Gross area [mm^2]
    
    # 2. Steel Properties
    # -------------------
    A_bar = 3.1416 * (d_bar/2)**2  # Area of one bar [mm^2]
    n_total = n_top + n_bot + 2 * n_side # Total bars
    A_st = n_total * A_bar # Total steel area [mm^2]
    
    rho = A_st / A_g # Reinforcement ratio
    
    # 3. Pure Axial Capacity (Simplified)
    # -----------------------------------
    # Phi factors would normally apply
    P_o = 0.85 * fc * (A_g - A_st) + fy * A_st # Nominal axial capacity [N]
    P_o_kN = P_o / 1000 # [kN]
    
    # 4. Pure Moment Capacity (Approximate)
    # -------------------------------------
    # Assuming tension controlled for demo purposes
    d_eff = h - cover - d_bar/2 # Effective depth
    a = (A_st/2 * fy) / (0.85 * fc * b) # Stress block depth (approx for half steel yielding)
    M_n = (A_st/2) * fy * (d_eff - a/2) # Nominal moment [N.mm]
    M_n_kNm = M_n / 1e6 # [kN.m]
    
    return locals()

class RCReportGenerator:
    """Generates HTML reports for RC Columns"""
    
    @staticmethod
    def generate_report(params, output_path="reports/rc_column_report.html"):
        """
        Generates an HTML report using handcalcs
        """
        # Ensure directory exists
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        # Run calculation to get LaTeX
        latex_code, results = calculate_column_capacity_latex(
            fc=params['fc'],
            fy=params['fy'],
            b=params['b'],
            h=params['h'],
            d_bar=params['d_bar'],
            n_top=params['n_top'],
            n_bot=params['n_bot'],
            n_side=params['n_side'],
            cover=params['cover']
        )
        
        # Build HTML
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>RC Column Calculation Note</title>
            <meta charset="utf-8">
            <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
            <style>
                body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 900px; margin: 0 auto; padding: 40px; }}
                h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
                h2 {{ color: #2980b9; margin-top: 30px; }}
                .calc-box {{ background: #fdfdfd; border: 1px solid #e1e1e1; border-radius: 8px; padding: 20px; box-shadow: 0 2px 5px rgba(0,0,0,0.05); margin: 20px 0; }}
                .meta-info {{ background: #ecf0f1; padding: 15px; border-radius: 5px; margin-bottom: 20px; }}
                .footer {{ margin-top: 50px; font-size: 0.9em; color: #7f8c8d; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }}
            </style>
        </head>
        <body>
            <h1>Thuyết minh Tính toán Cột BTCT</h1>
            
            <div class="meta-info">
                <p><b>Dự án:</b> VietStructFEM Project</p>
                <p><b>Cấu kiện:</b> Cột {params['b']}x{params['h']} mm</p>
                <p><b>Vật liệu:</b> Bê tông C{params['fc']} - Thép Gr.{params['fy']}</p>
            </div>
            
            <h2>1. Kiểm tra Tiết diện & Hàm lượng Thép</h2>
            <div class="calc-box">
                {latex_code}
            </div>
            
            <h2>2. Kết quả Sơ bộ</h2>
            <ul>
                <li>Khả năng chịu nén thuần túy (P_o): <b>{results['P_o_kN']:.2f} kN</b></li>
                <li>Khả năng chịu uốn thuần túy (M_n approx): <b>{results['M_n_kNm']:.2f} kNm</b></li>
                <li>Hàm lượng thép (rho): <b>{results['rho']*100:.2f}%</b></li>
            </ul>
            
            <p><i>Lưu ý: Đây là tính toán sơ bộ các đặc trưng tiết diện. Vui lòng xem Biểu đồ Tương tác đầy đủ trong phần mềm để biết khả năng chịu lực chính xác tại mọi điểm.</i></p>
            
            <div class="footer">
                Generated by <b style="color: #2980b9;">VietStructFEM</b> | Professional Structural Analysis Platform
            </div>
        </body>
        </html>
        """
        
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html_content)
            
        return os.path.abspath(output_path)
