from math import sqrt
from handcalcs.decorator import handcalc

# To make this works as a standalone script that generates an HTML file,
# we will use a slightly different approach compatible with python scripts
# (using the internal rendering mechanism or creating a Jupyter notebook structure).

# However, the simplest way to demo this for the user without Jupyter installed
# is to use the `handcalcs.render` functionality implicitly or mock it.

# actually handcalcs is best used in Jupyter. 
# Let's create a minimal script that simulates the output or uses the library's
# capabilities to export latex.

# A better approach for a script:
from handcalcs.decorator import handcalc

@handcalc(jupyter_display=False)
def steel_check(b, h, tf, tw, fy):
    A_f = 2 * b * tf
    A_w = (h - 2*tf) * tw
    A_total = A_f + A_w
    I_x = (b * h**3) / 12 - ((b - tw) * (h - 2*tf)**3) / 12
    W_x = 2 * I_x / h
    Z_x = 1.14 * W_x
    M_pl = Z_x * fy / 10**6
    return locals()

if __name__ == "__main__":
    print("Generating calculation note...")
    
    # Run the calculation
    b_val = 200
    h_val = 500
    tf_val = 16
    tw_val = 10
    fy_val = 235
    
    # The decorator returns a tuple: (latex_code, locals_dict)
    latex_code, results = steel_check(b_val, h_val, tf_val, tw_val, fy_val)
    
    # Create HTML wrapper
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
    <title>Steel Beam Calculation Note</title>
    <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <style>
        body {{ font-family: 'Segoe UI', sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; }}
        h1 {{ border-bottom: 2px solid #333; }}
        .calc-container {{ font-size: 1.2em; line-height: 1.6; background: #f9f9f9; padding: 20px; border-radius: 8px; }}
    </style>
    </head>
    <body>
        <h1>Thuyết minh tính toán: Dầm thép (Steel Beam)</h1>
        <p>Tự động tạo bởi <b>handcalcs</b></p>
        
        <div class="calc-container">
        {latex_code}
        </div>
        
        <h3>Kết quả:</h3>
        <p>Moment kháng uốn (M_pl): <b>{results['M_pl']:.2f} kNm</b></p>
        
        <p><i>Generated by VietStructFEM</i></p>
    </body>
    </html>
    """
    
    output_path = "examples/demo_calculation.html"
    import os
    os.makedirs("examples", exist_ok=True)
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_content)
        
    print(f"Success! Report generated at: {os.path.abspath(output_path)}")
